version: '3'

services:
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: password
    command:
      - "start-dev"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - keycloak

networks:
  keycloak:
    external: true


    
  
  

    